#
# Makefile for sys1scripts
# Copyright (C) 2009, by IPC, Fairfield, CT
#
# author: Chris Mosher
# creation date: 2009-01-16
#

#define the installation prefix
prefix := /opt/ipc/onems


VOBROOT := /usr/vobs

include $(VOBROOT)/ipc_build/include/script_component.mk
