/* Generated By:JavaCC: Do not edit this line. GedcomDateValueParserConstants.java */
package nu.mine.mosher.gedcom.date.parser;

public interface GedcomDateValueParserConstants {

  int EOF = 0;
  int FROM = 5;
  int TO = 6;
  int BEFORE = 7;
  int AFTER = 8;
  int BETWEEN = 9;
  int AND = 10;
  int ABOUT = 11;
  int CALCULATED = 12;
  int ESTIMATED = 13;
  int INTERPRETED = 14;
  int MONTH_LOWER_LIMIT = 15;
  int JAN = 16;
  int FEB = 17;
  int MAR = 18;
  int APR = 19;
  int MAY = 20;
  int JUN = 21;
  int JUL = 22;
  int AUG = 23;
  int SEP = 24;
  int OCT = 25;
  int NOV = 26;
  int DEC = 27;
  int GREGORIAN = 28;
  int JULIAN = 29;
  int LPAREN = 30;
  int RPAREN = 31;
  int NUMBER = 32;
  int SLASH = 33;
  int AT = 34;
  int RAWTEXT = 35;
  int BC = 36;
  int CALENDAR_ESC = 37;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"FROM\"",
    "\"TO\"",
    "\"BEF\"",
    "\"AFT\"",
    "\"BET\"",
    "\"AND\"",
    "\"ABT\"",
    "\"CAL\"",
    "\"EST\"",
    "\"INT\"",
    "<MONTH_LOWER_LIMIT>",
    "\"JAN\"",
    "\"FEB\"",
    "\"MAR\"",
    "\"APR\"",
    "\"MAY\"",
    "\"JUN\"",
    "\"JUL\"",
    "\"AUG\"",
    "\"SEP\"",
    "\"OCT\"",
    "\"NOV\"",
    "\"DEC\"",
    "\"GREGORIAN\"",
    "\"JULIAN\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "\"/\"",
    "\"@\"",
    "<RAWTEXT>",
    "<BC>",
    "\"#D\"",
  };

}
