Pazmiño-López Genealogy
=======================
Joseph Dudley
:toc2:

== Felicísimo López

``Felicísimo López was born in Quito on August 6, 1847, the
fourth son of Don Mariano Auz and Doña Dolores López, both of
Quito.footnoteref:[note1]
At the _Colegio de los Jesuítas_, he studied Latin under
Don Buenaventura Proaño, and Humanities under Padre
Herzáez;footnoteref:[note2]
he then entered the Facultad de Medicina in Quito, and received
his MD degree in 1872. (I have all his diplomas.) In 1873 he
moved to Jipijapa to set up practice:footnoteref:[note3]
two years later he married
Francisca Romero and they had nine children, not all of whom were
born in Jipijapa, however. In this town, birthplace of the straw
hat,footnoteref:[note4]
without giving up his practice, he opened and ran a shop,
as do many doctors on the coast, doing retail and wholesale
business.footnoteref:[note5]
In 1882, news came that General Veintimilla, in violation
of the Constitution, had declared himself _Jefe Supremo de la
República_.footnoteref:[note6]
López was so outraged that the same day he enlisted
as a `medic' with the patriotic forces that were already forming to
oust the dictator... (the political turmoils went on for some time,
and a man named Jose María Caamaño was named Interim President)...
when Caamaño was elected President in 1884, he adopted a policy of
terrorism against the insurgents; this obliged López to join the
revolutionary forces which were under the command of General Eloy
Alfaro, and the decisive defeat suffered at Jaramijó in 1885 forced
López, now `Surgeon General of the Revolutionary Forces,' to flee
to Peru.footnoteref:[note7]
It wasn't until 1888, when Antonio Flores was elected
President, that a general amnesty was declared and López was able
to return to Jipijapa and his family...footnoteref:[note8]''

``It was then that the Bishop of Portoviejo, Peter Schumacher,
began to accuse and denounce López in his sermons and pastoral
letters... in 1889 the family moved to Chone, where Dr. López set
up a new practice and began to write articles to `El Horizonte'
and the `Diario de Avisos,' large newspapers in Guayaquil, in which,
among other topics, he criticized the actions of this representative
of the church. This led to a judicial action against López and his
excommunication.footnoteref:[note9]
In 1892, he and his family moved to Guayaquil,
where he again set up practice and continued his journalistic and
political work. In 1894 he was elected Senator for the province of
Esmeraldas, but was denied, unconstitutionally, his seat in the
Congress because he was an excommunicant.footnoteref:[note10]''

``After the political transformation of 1895,footnoteref:[note11],
he was named
Colector de Rentas Fiscales (roughly tax-collector), a position he
held until 1900; he was elected Delegate to the 1896 convention
for the province of Manabí (where Jipijapa is), and went to Quito
[taking Nana with him, against Mamita's strenuous objections, so
that she could meet her relatives; the idea came from his brother
Francisco, Malvina's father. It was on this trip that Nana met Papa.]
At the beginning of 1900, Alfaro, now President, named López Consul
General in New York.footnoteref:[note12]
In October of the same year, he was named
Minister Plenipotenciary before the government of Venezuela, and
was given an honorary decoration by that country (Condecoración de
Segunda Clase del Busto del Libertador). He was later sent in the
same capacity to Nicaragua, and subsequently recalled to Ecuador as
first Minister of Education and later, of the Interior, which latter
position he resigned in August of 1901, returning to New
York.footnoteref:[note13]''

``In March of 1906 he was again named Consul in New York, which
position he held until in 1911 he was summoned by Alfaro to Quito
to be Minister of the Interior again... he was there for the 1911
revolution.... After January 28, 1912 (when the clergy and the
Conservatives staged a bloody coup in which Alfaro and other
Liberal political figures were massacred) Dr, López's life was in
danger, and when it was safe for him to leave his hiding place,
he left Ecuador permanently and settled in New York, where he
died on December 15, 1917. He is buried in Evergreens Cemetery,
Brooklyn.footnoteref:[note14]
There are other data: he was thrice a member of the
City Council of Jipijapa; a member of the board of the
Quito-Guayaquil Railway; Ecuadorean _Charge d'Affaires_ in Washington;
a delegate to the International Conference on Industrial Property
Protection held in Washington in May, 1911; and finally, a member
of the Venezuelan Academy of History. In 1901 and 1910 he declined
his nomination as candidate for the office of President of Ecuador.''

He wrote a number of books and pamphlets, articles, etc.,
of which the most important are: the first complete Atlas of
Ecuador, published under his supervision while he was Minister
of Education; _Historia de una excomunión en el Ecuador_, New York,
1909, and _Virutas_, New York, 1908. _Virutas_ means wood shavings, or
chips; for Chirstmas 1905, López received from his son Miguel Angel a
diary, and every day he wrote down a thought, imitating one of his
literary heroes, Victor Hugo; the book is a charming collection of
_pensées_ ranging from the philosophic to the purely anecdotal.
For our purposes, perhaps his greatest contribution to humanity was
Nana, who encarnated the ideals of personal integrity by which
he lived.



footnoteref:["note1",
"This biographical sketch was extracted (translated and edited
by me) from ``Personalidades Ilustres de la Medicina Nacional'' by
Luis A. León, an article which appeared in 1951 in _Papeles Médicos_,
the organ of the local (Quito) equivalent of the A.M.A. It was just
one of the many times over the years that someone has taken an
interest in Felicísimo López's life and has written on some aspect
of it. There is a town called Puerto López somewhere on the coast
of Ecuador, and in the early 60's, Eloísa, who was then living in
Quito, was present as Guest of Honor, as López's only surviving
child, at a gala in his honor at the Quito Press Club's Hall of
Fame, for which she supplied some material. Professor Justino
Cornejo of the Facultad de Historia de la Universidad de Guayaquil
did a monograph on López around the same time. The list goes on, and
will probably continue to do so, since López's excommunication and
subsequent expulsion from the Ecuadorean Senate made quite a _cause
célèbre_; he is something of a hero in the history of civil rights in
Ecuador. Since illegitimacy is not a particularly heroic condition,
when Eloísa was approached for biographical data for this article,
as well as all the others, most probably, she gave as Felicísimo's
father's last name López. As a perusal of the charts that preceded
these ramblings will show, his name should have been given as
Mariano Auz.
This worthy was a priest in the monastery-church of La Merced.
He was famed a very learned man (the earliest family member who is
recalled as possessing this very family trait) but extremely
conservative and pious. Piety among clerics in Ecuador then, as
elsewhere and at other times, was a rather relative thing, and many
priests had children; some openly maintained homes, or some sort of
family establishments. (Curiously enough, the same didn't apply to
nuns; if they violated their vows, they were discreet about it.)
One of Nana's neighbors in Jipijapa, when she was a little girl,
was a priest named Ontaneda and his family. Mariano Auz, _Father_
Mariano Auz, had by Dolores López five sons (chart 5); there was
also a much older half sister, on whose side I don't know, named
Rosario Daste, though the last name Daste, rather than López, would suggest
that Father Auz had known other ladies previously, since _hijos
naturales_, especially when they were also _hijos sacrílegos_, were
almost always given their mother's last name. All five brothers
loved Rosario Daste, who was like a second mother (I know nothing at
all about Dolores López, when she died, how, etc.) and who was
lamentably killed by a stray bullet in some remote political skirmish
in Quito. The family lived in la Casa del Cebollar, named after the
hilly street on which it stood, and which once ended in a large
field planted with onions. It was still standing in 1959, when I
saw it and took a couple of pictures of its thick walls, but it was
no longer owned or lived in by anyone related, and the neighborhood
was in the most obvious state of irreversible decline.
The piety and intelligence of Mariano Auz were, according to
Nana, unfortunatley accompanied and surpassed by an inhuman paternal
severity which can only be described as sadistic. Felicísimo told of
a room in this house, completely empty save for a large stake firmly
embedded in the middle of the floor. The slightest real or imagined
infraction by any of the five sons was instantly punishable by being
tied to this post and thrashed. (One wonders whether Rosario Daste
ever got the treatment as well.) Auz was a Dominican, and the picture
I have of him, and will hopefully be able to locate, shows a face
one would not relish meeting in a dark alley. Miraculously, the
boys survived all this and came out of it with an eduring distaste
for any sort of paternal physical abuse and a great appreciation
of the duties and responsibilities of parenthood vis-à-vis the
love of one's children."]
footnoteref:["note2",
"Both Proaño and Hernáez were renowned educators of the time."]
footnoteref:["note3",
"Quito was full of doctors, and Felicísimo's brother Carlos
wrote from the coast and suggested that the privince of Manabí,
rural and still backward, needed doctors."]
footnoteref:["note4",
"``Panama'' hats are really made in Jipijapa. They became very
fashionable here after the Panama Canal opened up new avenues of
trade. I don't think Ethel Merman would have signed a contract to
sing in a musical called ``Jipijapa Hattie.''"]
footnoteref:["note5",
"Jipijapa (Hee-pee-háh-pah) is a town, and a small one at that,
but it's situated at a main crossroads point... the road is still too
primitive to merit the term highway junction. Felicísimo ran a sort
of general store to make ends meet in this semi-arid tropical
backwater."]
footnoteref:["note6",
"Sounds familiar. _Jefe Supremo_ was one of the official titles
of the president, though not necessarily indicative always of an
electoral victory. I think Franco was styled _Jefe Supremo del Estado
Español Generalissimo_ Francisco Franco, etc."]
footnoteref:["note7",
"He was there three years, and was friendly with the intellectual
circle of Liman society and Peru in general, among whom Ricardo
Palma, famous Peruvian short story writer, à la Mark Twain. He also
managed during this time to father a son by some _tapada_; he brought
the boy back with him in 1888. Mamita, who had always taken a dim
view of Abuelito's political heroism (or heroics, if you please),
took even greater umbrage at having to raise this unanticipated
addtion to her own brood. His name was Carlos, and was described
to me by Malvina, (through whom I first heard of his existence) as being
very dark, but the image of Felicísimo. He never really felt
comfortable with Mamita, though the children liked him (why not, after
all?) and called him _ñañó_, roughly, ``little brother,'' affectionately.
When the family moved to Guayaquil, he moved out on his own, dropped
out of sight, and I suppose got married and had a nice life. I shall
always find it curious that neither Nana nor Eloísa ever mentioned
him to me, since they never scrupled to tell me about similar cases
among their uncles, and about Auz. I suppose, if the story is true,
and why would Malvina invent such a whopper, if such it is, that
Nana felt it might tarnish the idealistic image of Felicísimo she
was handing down. Personally, I find it reassuring to think that the
idealist was also human. At any rate, as the Italians say, _si non
è vero, è ben trovato_... if it isn't true, it makes a good story."]
footnoteref:["note8",
"But, in 1887 a disasterous fire had devistated the town; there
were three victims: an old maid and her neice, and Rosario Romero,
Nana's grandmother. More on this incident elsewhere."]
footnoteref:["note9",
"This need a footnote. Abuelito was a _feuilletiste_ in true
19th century style. In places where not too much happens, newspapers
carried more features, articles, essays, reviews, etc. This was in
the days before advertising covered 80% of a newspaper's space.
Communications then were bad, and intellectuals exchanged their
opinions and ideas in essays which were frequently cast in an
epistolary form to the Editor, or in the form of a dialogue. In
one such exchange, Abuelito signed with the pseudonym ``Zisca,'' and
a friend of his always used ``Athos.'' Some of these were long Letters
to the Editors expressing political opinions. If the powers that
be disagree with whatever one is saying, they call it propaganda.
Ecuador was almost a theocracy at this time; all civil records were
kept by the church, which was also the only tolerated religion;
ecclesiastics sat in the National Assembly, and there was no lay
education; all schooling, such as is was for the masses, was under
the control of the church. It was all very corrupt and oppressive, and
people could be sent to prison for anitclericalism, which was
judicially punishable as heresy. (Did you know, for example, that
as late as 1875 a village priest in Peru burnt an old woman as a
witch? Admittedly, an extreme example, but it gives an idea of
the times.) In some of his articles, López criticized Bishop
Schumacher for several abuses, among which the most resented was
his prohibition to the local peasants against holding market on
Sunday. Schumacher was German, one of many foreign clerics the
Curia imported to fill higher ecclesiastical positions; most of
these clerics were ignorant of locally senctioned customs.
Schumacher's idea of the Sabbath was more Baptist than Catholic
(or more Methodist, or Calvinist, whatever... i.e., the seventh
day all you do is go to church) and failed to take into account
that his abrogation of the customary Market-on-sunday-in-the-plaza
tradition imposed great hardship on the peasants, who now lost a
day's work, and under pain of mortal sin, let it be added. When
Schumacher, in the same newspapers and from his pulpit, cited
passages of Scripture to validate his position, López, who had
after all studied with the Jesuits, was able to reciprocate in
kind and totally refute the bishop's point. Wonderful book, the
Bible; one can make it say exactly what one wishes. At any rate,
this went on for a while, until López made the fatal tactical
error of referring to the church as a ``Christian sect,'' which is,
after all, what it is. But in those days is was the Holy, Roman
and Apostolic Church, officially so, and Schumacher jumped at the
opportunity of ridding himself of another ``liberal Masón'' via a
Bull of Excommunication, so aptly termed. He declared
López an excommunicant ``vitandus,'' which means that not only is he
deprived of the sacraments and God's love and all that, but all
faithful who deal with him incur mortal sin. López was a doctor
amidst superstitious rednecks; it ruined his practice.
But not everybody was peasants, and popular opinion was
strongly behind López. A group of Liberals in Portoviejo, capital
of Manabí, spread printed copies of Schumacher's Bull on the ground
between the church and the rectory one rainy day so that he would
have to grind his words into the mud as he went to say Mass.
There was, however, a lot of rednecks, and López's life was,
strictly speaking, in danger."]
footnoteref:["note10",
"López left the extremely documented and complete account of it
in his _Historia_, which was published in Spanish, and copies of which
are in the New York Public Library and the Library of Congress.
Having frittered away a number of years in my youth in studying
Hispanic literatures, I feel qualified to venture an opinion.
He has very fine style; in the _pensées_, (_Virutas_), he tells anecdotes
that I heard from another first hand source, Nana, so I'm familiar
with the details and can concentrate on the presentation. Very
nicely done, warmth, taste. In the political writings, the rhetoric
is very nicely constructed, and one gets the impression of great
honesty. Too bad he never did fiction per se, or wrote on
international rather than just local affairs, of limited transcendence."]
footnoteref:["note11",
"After a political scandal à la Watergate involving the sale
of the use of the national flag for a ship of the navy of a country
then at war with someone else, there was a revolution and the
Liberals were swept into power by popular election. The new
President was Eloy Alfaro, for whom Eloísa was named, and who was
Victor's godfather. It began an enormous social revolution, but
not a bloody one; a good comparison, up to today at least, might
be Spain after the death of Franco. Sweeping reforms at all levels
were implemented."]
footnoteref:["note12",
"López wanted his younger sons (Miguel Angel, Aquiles and
Samuel) to be educated in the U.S., a country whose estensible
political and intellectual freedoms he greatly admired. He asked
for the job, and got it. It was a sinecure; his ministerial and
diplomatic activities were more important. He, Nana, Papa, Victor
(aged 8 months) left Guayaquil on February 1, 1900 and arrived in
New York on the 14th. In those pre-Canal days, one sailed to the
west coast of Panama, took a train across, and boarded another
ship on the Atlantic coast. They arrived at night, and in those
happier and more trusing days, foreign diplomats had courtesy of
the port, and one just gave the number of one's entourage, perhaps
the names, somebody wrote it down, and that's that. Nana used to
say that there was no record of her being in this country until
FDR days and the Alien Registration Bill. They never became citizens,
Nana and Papa; about Papa, I don't know, but I'm sure it was
like Nana. She was proud right down to her last day of her still
valid Ecuadorean citizenship. She never wanted to come here,
never liked the idea, and used to bemoan her abject decline,
which would have been impossible in Ecuador. She was right, too.
The party spent that first night at the Fifth Avenue Hotel,
the Waldorf of its day, at 23rd Street. Abuelito and Papa want to
the Metropolitan Opera to see _Carmen_, with Calvé, I believe, and
Nana was left to the baby and the whoosh-whoosh of the ladies' long
skirts in the hallway. The rest of the family, including Mamita and
Malvina, sister-cousin Malvina (Dolores), see chart 5, came a year
later, Malvina to enter that Fall the Moravian Seminary in Bethlehem,
Pennsylvania, a normal school. Aquiles was 13, Miguel 15, and Sam 8."]
footnoteref:["note13",
"In his absence, Papa was Acting Consul. It was a comfortable
situation, and to the advantage of the Ecuadorean government, because
they were both good, efficient civil servants, and they were honest.
It's too bad they were, in a way, because a Consul can get graft if he
wants, and there's always someone who wants to give you money in
return for some favor. They never got anything off the top, as it were,
because there was nothing left when the revolution curtailed their
regular salary, and that was the beginning of the end. Neither of
these two gentlemen was equipped to handle any other kind of job.
Victor was 13 (1912), Miguel was back in Ecuador, Aquiles I think
in Argnetina, and Sam was 21. And later that year Amalia, Papa's
mother, died, requiring his immediate return and protracted stay.
Insult to injury: Eloísa had a boy friend, American Protestant
type doctor. Eloísa was very beautiful as a young woman
and retained it into her eighties and death. But when the good young
doctor learned that López was no longer a real-live furriner diplomat,
he stopped calling. The cad."]
footnoteref:["note14",
"Of rectal cancer. He was in full control of his faculties, and
had all his teeth save one wisdom tooth, and all his hair. The cad.
I have the deed, someplace, to the plot, which also contains Mamita
and Sam."]





== Francisca Romero

The running quotes at the end of this section I translated
and heavily edited from: _Orígenes del Ecuador de hoy: García
Moreno_ by Luis Robalino-Dávila; Quito, Talleres Gráficos
Nacionales, 1948, pp. 3-12. This is a biography of Gabriel
García Moreno, who was a President of Ecuador in the 19th century.
An extremely able administrator, and probably honest, he was
ruthless in his attacks on his opponents, and his politics
were somewhat to the right of Ivan the Terrible. He was also
a religious fanatic, and during one administration changed the
name of the country to the Republic of the Sacred Heart of Jesus
and gave it as a fief to the current Pope. It was he who was
largely responsible for the importation of foreign clerics
mentioned earlier. He was finally assassinated in 1875 on the
steps of the Palacio de Gobierno in Quito, to the great relief
of many. All this is germaine only because he was alos Mamita's
uncle.

The García Morenos were of the ``aristocracy'' of Guayaquil,
very rich, very conservative, and very Catholic. Juana Mercedes
Moreno Morán de García Gómez (chart 4) was carried every day to
Mass, in her very old age, on a sedan chair by four servants,
and Manuel Ignacio, Gabriel's brother, was a preist. Sent to a
parish in remote Jipijapa, he took along one of the family servants,
a girl named Rosario Romero (Mamita's mother), and before you
knew it, they had five children: Pedro Alcántara, Ignacio, Tomás,
Francisca and Mercedes. At some point, he left for another see
and Rosario and the children stayed. Again, per custom, the latter
took their mother's last name. Pedro Alcántara had a homonymous
son who died at age 17 in a revolution; Tomás married and lived in
Guayaquil; Ignacio went to Guayaquil too, and was supposed to
come visit the family in Brooklyn around 1908, but vanished
without a trace after sending a cable saying that he had arrived
in Panama; and Mercedes had two daughters by as many men and died
in Guayaquil during an epidemic of bubonic plague in 1913. One
of these daughters was Rosario González (she did take her real
father's name, as did her half sister Rita Alencastro), who in
similar fashion had a daughter named Delia Maruri. Nana and Lola
kept in touch with Rosario until her death from cancer in 1960 or
so. Delia married a man named Eduardo Rossi Guerra, they had a few
children, some now married; they live in Guayaquil and are very
nice middle class people.

Though married to an ardent ``free-thinker,'' Francisca (Mamita)
retained her Catholicism more or less active, until her death at
90 of natural causes. She was an intelligent but not an educated
nor enlightened lady; nor was she a lady with whom one might deal
flippantly. When someone affectionately called her Mama, she would
say something to the effect of, ``Don't call me mama; I'm not your
mother.'' Later, when she had warmed to the person, the greeting was
``Hello, my son.'' She never saw a movie, for superstitious reasons.
All in all, she didn't have such an easy time of it; first there
were Felicísimo's idealistic peradventures, which left his wife
and children in desperate straits; then there was the revolution
in 1912 and all that meant; all her five sons died before she did
and she had money worries all her life. The picture shows her at
age 51; she was thought to be a great beauty in her youth, because
of her fine delicate features, which were her García Moreno legacy.
She looked very much like her dictator uncle, whom she probably
never met. Her father probably left home (rectory) when she was
very little.

Francisca's mother, Rosario Romero, lived with her daughter
and son-in-law in Jipijapa. She took care of the children shile
Mamita's time was taken up with running the store during Abuelito's
exile, (1885-88). In 1887, when Nana was ten, some kids were
playing with matches, and the better part of the town, which was
all cane and straw, went up in smoke. So did three ladies: an old
maid and her niece, and Rosario Romero. Nana recalled the
catastrophe vividly all her life. As the flames inexhorably approached,
Mamita and Rosario Tomero were trying to save as much as possible
from the store. Mamita went to find a wagon and Rosario took the
children to a surrounding hilltop and told Nana to make sure none
of them moved from the spot until her return; she was going to
find Mamita. When Rosario returned, she was naked save for a petticoat
someone had given her, and burnt all over. Nana said Rosario
said nothing until she saw Mamita and told Nana to call out. When
Mamita saw Rosario, she called for help, but since Abuelito, the
only doctor, wasn't there, all that could be done for the poor
woman was to apply linseed oil with cotton to her burns. She died
in agony that night. The story goes that when she returned to the
store, she saw that the family's goat was still tothered and
desperately trying to free itself, since the thatch roof of the
stable was ablaze. Taking pity on the animal, she went over to
untie it and the roof caved in on her. When they managed to pull
her out, all her clothes had been burned away.

There are some interesting details about Rosario Romero:
She was _mestiza_, like just about everyone else in town, but was
very dark, and clearly of a different ethnic mixture than anything
common in the region. Also, according to Nana, she spoke Spanish
with a slight accent. Guayaquil was an important seaport (despite
its inland position on an estuary), so Rosario could have come
from just about anywhere Spanish or Portuguese were spoken.

Now for the quotes from Robalino's book. Please bear in
mind that Robalino is obviously enamoured of his subject, and
talks about these remote forbears as if they had as many
quarterings as an Austrian Archduke, and as if Guayaquil were
the Byzantium of South America.

``Miserable Castille, one powerful... Castille of grey rocks...
dusty Castille covered with saffron plants... this was the native
land of Don Gabriel García Gómez... Villaverde del Monte is three
leagues from Soria... a poor village of 53 souls (1948), though
the entire parish has 250... a poor place, but in a land of epics
(this is, after all, the land of Don Quixote)... here was born
Don Gabriel García Gómez October 2, 1766, who was baptized the
13th. He was the legal son of Don Diego García Yanguas and Doña
María Gómez, natives and residents of Villaverde. His paternal
grandparents were Don Juan García Yanguas [I think there's another
shady parentage here... these two men shouldn't have had the same
maternal last name Yanguas, but...] and Doña Josefa Martínez.
This lady was born March 27, 1652, the daughter of Don Alonso
Martínez and Doña Catalina Escribano, baptized `privately' that
same day `because of necessity' [no idea what that means]; her
godmother was her grandmother Doña Ana de la Orden, `due to the
lack of a godfather' [that sounds clear enough]. Don Gabriel
García Gómez's maternal grandparents were Don Juan Gómez and
Doña Cecilia de la Orden,
which shows that his parents were interrelated. His godfather
was his maternal grandfather Don Juan Gómez, and the certificate
was signed by Father Manual García Aragonés (probably another
relative).... His parents were married [hooray] by Father Joseph
Cueto, priest of Cidones, November 22, 1762... there were in all
probability more younger siblings... one came to Mexico and was the
founder of the family that eventually produced the famous historian
García Icazbalceta.... The origins of these families are very old....
They were, probably, poor _hidalgos_ who had just enough land to
keep them fed.... He studied in Cádiz at the home of his uncles
Don Juan Simón and Don Melchor Martínez de Aparicio, who had some
commercial enterprises in that port city of Spain. The Martínez de
Aparicio traced their family back five generations; they were
Lords of the House of San Bartolomé del Cerro in Sotillo (Soria)
and proved their nobility before the Tribunal of the Royal
Chancellory of Granada and were granted a Royal Provision on March
22, 1776. They requested and were granted by Don Ramón Zazo y Ortega
a charter with their coat of arms on August 27, 1778... [He then
goes on with some lengthy details about these Martínez, which don't
really concern us here.] And one fine day in 1793 while Spain
and all Europe were shuddering with fear at the news which kept
coming from France [the French Revolution, Napoleon, etc.]; urged
on by the fear that the Terror would cross the Pyrenees, and helped
financially by his uncles in Cádiz, he bought goods for trading
and boarded `Nuestra Señora de las Nieves,' a frigate which was
leaving for the colonies... a Spaniard newly arrived from Spain
was in those times superior to the creole, contaminated now by
the tropical laziness of the climate [Guayaquil is not what
one might term a tropical paradise] and perhaps even by some
shadowy _mestizaje_ of his ancestors. The creoles who had not
intermarried preferred, naturally enough, native Spaniards for
their daughters... add this fact to Gabriel Barcía Gómez's
natural good looks, industry, references and ambition, and it is
not hard to understand why the _Regidor Perpetuo del Cabildo de
Guayaquil_ (the local potentate), Don Manuel Ignacio Moreno y
Sylva Santistevan, and his wife, Doña Manuela Morán de Butrón
y del Castillo should heartily approve of the interest the
young man took in their daughter, Juana Mercedes.... The _Regidor
de Guayaquil_ was the son of Don José Ignacio Moreno and Doña
Ana Manuela de Sylva Santistevan y Larralde, whose good lineage
is evidenced by his permanent position as _Regidor_... [there
follow some more lengthy details about these good people.] Juana
Mercedes was born in Guayaquil in 1780 and married Gabriel García
Gómez in 1797; they had twelve children. The eldest, Josefa
Dominga, born in 1798, died at 47; Concepción, at an early age;
Manuel Ignacio followed the ecclesiastical career [this was
Mamita's father]; Mercedes, dead at 18; José, died young; the
second José studied Catholic liturgy, but later married María
de los Angeles Mateus y Vásmezon [not a Spanish name] and lived
to be 71; Carmen, no data; Miguel, one-time Governor of Guayaquil;
Pedro Pablo, landed gentleman and businessman; Fernando, no data;
Rosario, likewise. The youngest was Gabriel García Moreno.''

As the last of all these details, it should be mentioned
that Doña Juana Mercedes, of sedan chair fame, lived to be 91
and was all her life a ``Tory;'' after Ecuador gained its independence
from Spain in 1822, she continued to hang the Spanish Royal
Flag on her door every Independence Day (August 10) until her
death. Like Mamita, her granddaughter, she was longlived and
feisty.

N.B. Last year Enid and her husband Aurelio came to San
Francisco and I met with them; we took a sightseeing bus around
town, despite the unfortunate rain and fog. At one point Enid
buttonholed me and said that Aurelio, who among other things has
been a history teacher, and a Spanish Literature teacher at some
midwestern college here, thought Garcia Moreno was the worst thing
that ever happened to Ecuador, and would I please not blab any
of these scandalous genealogical details to him. I agreed.





== López-Romero Family

Having some time ago set down numerous details of some of
our progenitors, I should now show you their children. The
preceding picture was taken in Brooklyn in 1911, the last year that
all surviving family members were together. At some point I'll
sort things out and send pictures of the two missing brothers
[I've found them and include them herewith],
but for the time being, this _précis_: to the left of Felicísimo
is Eloísa (see charts for dates, etc.), who never married and died
childless. Standing above her is Miguel, who mever married but was
the father of Enid, Olga, Ulises, Alicia, and two others who died
in childhood. Miguel was the only son to go back to live in
Ecuador, settling in Guayaquil; when he died in 1935, his cousin
Malvina adopted his children and brought them to Quito, where
Olga and her family live still. Enid lives in Guayaquil, and Ulises
in New York state, West Hempstead, I believe. Alicia, who was
brought up not by Malvina, but by Miguel's ``wife,'' a lady named
Enid Espinosa, who lives or lived in Loja, in Ecuador, may or not
still be alive in Mexico, where she was the widow of a military man
of some sort of rank. Miguel refused to accept her as his daughter,
though she was of all the children probably the one who looked
most like him.

Back to the picture: standing next to Miguel is Dolores (``Lola''),
who married a German named Frank Zilker, from Munich. They had one
daughter, also named Dolores, (``Lolita''). Zilker was a widower with
three children, one of whom was the wife or girl-friend of a man
named Malcolm Stevens, whose sister Ruby eventually became...
Barbara Stanwyck! The girl, Elizabeth (``Sissy''), eventually died
of TB, and Stevens eventually changed his name to Stanwyck. Lola
and Zilker didn't make it as a marriage and she finally left him in
New Orleans, where, I think, he died in the mid-forties. Fate is
funny; somehow, in a trunk of old papers from Glenwood Road, I found,
and still have, Barbara Stanwyck's elementary school autograph book
from Brooklyn. I guess I should send it to her before either of us
dies. Wonder what she'd say if I asked her how her brother Mal was.

In the picture again... standing above Mamita is Aquiles. In
New York, I believe, sometime around 1911, he married an American
girl named Bessie. They had one son, Robert (``Bob'') López, who
if still alive now (1983) is about 71; last I heard he was living
in LA, divorced. He had some kids too. Aquiles and Bessie didn't make
it as a couple either, and went their separate ways. Bessie remarried,
a man named Joe Cohen, who was involved with the movies somehow, as
was his stepson Bob López. I remember seeing the name in the credits
of some films, I think Paulette Goddard's deathless impersonation of
Jezebel was one of them. Something in the technical aspect, cameras
or film. Bob visited his cousins in Brooklyn in 1939, and took several
very fine family shots. Judging from the pictures, Bob looked a little
like Mamita. Aquiles left New York and finally wound up in Buenos
Aires, where he was one of the editors of a paper called _La Nación_.
He was a man of some prestige and a bit of a man about town. (At this
time Eloísa and Mamita were living with him.) Too much town, too much
high life and champagne and tuxedoes; after a party one hight in 1929,
he was in the back seat of a car, being driven home by some friends.
They noticed that he had stopped talking and turned around to find
that he'd just plain dropped dead of a heart attack. Mamita and Eloísa
came back to Brooklyn, where she died in 1940. Eloísa finally went
back to Ecuador in 1960 or 61, and died in Quito in 1965.

To the right of Mamita is Samuel, the youngest of the family.
He served in the Canadian forces in Europe during WW I, and wound
up living in Maracaibo, Venezuela in the twenties. There he married
a girl whose name I forget now; her last name, though, was Villanueva.
She was very dark, I've been told; they came to visit NY on their
honeymoon. Her family didn't like Sam, and the feeling was mutual.
I think this was in part because the girl wasn't very healthy and
her parents had hoped she wouldn't marry. But she did and they had a
daughter, Margarita Cecilia, born around 1924. Sam worked for some
oil company and was in NY on business alone when he got news that his
wife had died. When he went back to Maracaibo he told his in-laws that
he wanted to go back to NY and take the little girl with him, to which
they were adamantly opposed. So opposed, in fact, that they took the
little girl and skipped out, vanished. Sam was never able to find them
and eventually died in Brooklyn in 1933.

There is an anecdoe to Sam López's life and death. He suffered
from a mild form of epilepsy; you'd be talking with him and he would
occasionally drop off into a little mumbling or silence for a few
moments and then come right out of it. This condition, which was probably
responsible for his being in the Canadian forces rather than the
American, became more pronounced as he grew older; it would happen with
increasing frequency and for longer periods. He was diagnosed as having
a benign brain tumor and decided to have surgery. Some might say the
risks, even in this country, were great in the thirties, but I guess
the increasing inconvenience was worse, so he was operated on and died
of complications. The anecdote is this: the afternoon before the surgery
he and Papa, his brother-in-law (Víctor Manuel Pazmiño, for you
younger ones), were sitting on the porch swing talking when the
Shakespeare clock on the living room mantle struck, and struck, and
struck, over and over until it went sproing and stopped. Since the
clock had run perfectly ever since Felicísimo and Francisca had bought
it in 1900, 33 years earlier (it was part of the home furishings of the
outgoing Ecuadorean Consul General, and I have it now), it seemed
not unusual that it should break down. Nana always said that this
extraordinary coincidence was an omen that was ignored, and I think
she was right. She told me that she had taken it to a couple of
clocksmiths, but they couldn't find anything wrong with it. It
didn't run again until 1969, when I had it repaired in Boston. It
still ticks and chimes on my mantle now, but several years ago the
strike mechanism went awry, and now it's anybody's guess how many
times it will strike every half hour. I find this perversely
humorous and have yet to have it looked at.

And that brings us to the upper right hand figure in the picture,
Nana, Lelia, who deserves a book in her own right. She married Papa
in Guayaquil in 1898; there were eight children, the Pazmiño López
family of chart 1. I should mention that in Latin America it's the
custom for people to use their mother's maiden name after their
father's family name, much as it was the custon in this country
years ago to use this same maternal maiden name as a middle name,
cf. Franklin Delano Roosevelt, Ulysses Simpson Grant, etc. I've
followed this custom for this essay, to keep things straight. I
should also mention that whereas in the US cousin is used for just
about everybody besides siblings and nephews, etc., in South America
a different system prevails. For example, Stella Pazmiǹo Disosway's
children Kenneth and Linda are first cousins to Grace Pazmiño
Ganley's daughter Joan, as they are to me, son of Lucile Pazmiño
Dudley. Linda's children and Joan's are second cousins to each other,
but to childless me they're first cousins once removed, as I am to
them. Joan's daughter Leslie's children are first cousins twice
removed to Kenneth, Linda, me, etc. And Leslie's grandchildren
would be thrice removed, and so on. In Latin America, a different
terminology is used, whereby Joan's children and Linda's are my nieces
and nephews _en segundo_, ``second nieces,'' and I would be their _tío
en segundo_, ``second uncle.'' Another example: Lolita is Grace's first
cousin, right? Lolita is therefore _tía en segundo_ to Joan, (first
cousin once removed), _tía en tercero_ (twice removed) to Leslie, and
_tía en cuarto_ (thrice removed) to Leslie's children, and so forth.
Not too confusing, if you think
about it, and all it is is a different way of describing that kind
of family relationship. In Ecuador one would say all these people
are uncles, nieces, etc.; here one would term them all cousins of
some sort since even the distinction between first and second cousins
is almost beyond grasp. And as a final example of the American system,
to confuse you all, I can mention that since Lolita and Grace, (and
Stella and Albert, etc.) are first cousins, then Dennis is second
cousin to Joan (and to me, and Laura Lou, and Georgiann, etc.). Dennis
lies in the same relationship to me and my first cousins as do the
childen of Olga, Ulises, Bob López, not to forget whatever children
that long lost daughter of Sam López might have had.

But now I have to jump back a bit to Ecuador because so far I've
only written about Nana's line and that's only half the story. Some
details must be given about the Pazmiño side, and the best character to
begin with is his mother, Doña Amalia Hurtado.

But before I do that, I must first comment on the pictures of
two young men, set in ovals, and printed by Bauland's of Brooklyn.
These are two López Romero boys who had died before the 1911 portrait
was taken; theyu were Estenio and Ulises, and you can see where they
fit on the appropriate chart, No. 1. Somebody must have taken earlier
photos to have these made from them; I would assume that it was
Mamita. There isn't too much to tell about them, since they died so
young. Estenio was Nana's favourite brother and Abuelito's favourite
son; he had the same high ideals and liberalness of thinking that was
so characteristic of that family, and was moved by patriotism to go
off and fight with liberal revolutionary forces, dedicated to the
overthrow of some dictator (not García Moreno, another one) before
the final victory of Eloy Alfaro and the Liberals in 1895. Unfortunately,
he got shot and died on the battlefield. Mamita was dead
set against the idea, but there was no discouraging him. Heroic
deeds, yes, but living is nicer. remember, Mamita had had to deal
with a lot of misery while Felicísimo was exiled, and now she loses
her first son. Hard.

Ulises died as a result of some violent intestinal infection
that struck him and Eloísa when the family was living in Guayaquil.
Eloísa got better, but as some will recall, always had some sort of
trouble with her digestion. I don't remember any stories about him,
though I'm sure Nana or Eloísa had some to tell me. I find the
resemblance of Estenio to Nana very striking, but that's because
I've seen so many pictures of Nana when she was a yound lady. As I
continue to go through my closet, I'll xerox some of the better ones.

I should mention that those of you who don't have any direct
memories of Nana or Lola, say, i.e., Linda's, or Joan's younger kids,
could get the impression from the reproductions that these people
were more darkly complected that they really were. Lola nad Aquiles
were nicknamed the ``negritos'' by their siblings, but for the most
part, despite the strong Indian features, notably the shape of the
eyes, both sides, López and Pazmiño-Hurtado were quite fair, very
``white'' looking, if you will. Many of the pictures have darkened
with age, and xerography, while cheap, isn't the best kind of
reproduction. As for the true ethnic or gene background, I can say
this: it's predominantly white, with a strong Indian strain and just
a little bit of Black, this latter bit of spice being the legacy of
the formidable looking lady whose tale I'm finally getting to, as
follows.





== Amalia Hurtado (Donoso) and Francisco Mariano López

This redoubtable looking but very good lady was Papa's mother
(and Malvina's too) and was born in Quito in the laste 1830's or early
1840's. Her mother was named Dolores Zambrano and was the wife of
Joaquín Donoso Baen [sic, actually Donoso Ortiz] (Chart 2);
but this gentleman was not her father. That
distinction belongs to a man whose last name was Hurtado and who was
the 19th century equivalent of a Fuller Brush man, travelling from
town to town selling hardware and dry goods. Doña Dolores probably asked
him in to show his wares one day and got more that she perhaps (only
perhaps) bargained for. Anyway, thence Amalia, who fits into forth
place among the legitimate and not so so children of Donoso and Dolores
Zambrano (their names were Camila, Modesto, Teresa, (Amalia, and) Adela).
I have a whole list of names of the descendants of these worthies, but
there has been no connection for decades, so really, why bother?

Predictably, Hurtado wasn't seen again; it _was_ known of him, though,
that he was from the coastal province of Los Ríos, where blacks
constituted a large part of the population. A footnote: in the Andean regions,
places of very high altitude... Quito 9500 feet..., there are very few
blacks. There is every tint and hue and whatever of white and Indian,
but there are almost no blacks. Amalia is quite different from all the
other Donoso children, who are, from the pictures I've seen and two first
cousins of Papa's, nonagenarians both, whom I met in 1969, almost all
white. The picture of her shows her in old age; in an 1860's tintype I
saw in Quito, a hoopskirt and ringlets enhanced the figure of an
extremely handsome and attractive young lady. It wasn't a beautiful face,
but it was very striking. Insofar as one can trust appearances, she was
the source of the curly hair and the "Pazmiño" forehead. Everything I
can remember being told about this lady by Nana or Malvina points to
a very loving but definitely no-nonsense kind of lady, with a shrewd
business sense. I have always thought it highly deplorable that this
most desirable attribute didn't come with the forehead.

At any rate, sometime in the 1860's she met and married José
Manuel Paz y Miño, who was considerably older than she; they had
several children, most of whom died in infancy. Those who survived
were three; Diocelina, Rosario and Víctor Manuel (Papa), who was
born posthumously in 1871. (I don't think that's correctly used, but
anyway...) This Paz y Miño belonged to one of the oldest and richest
families in Quito, about all of which more later, and he was
not in the best of health; I've been told that he had kidney trouble
or liver problems, I don't recall which; I've also learned that this
was quite common in those days before that water purification plants
made things a bit nicer. Or that might have been someone's euphemism
for boozers. No telling at this point.

It should be mentioned that these Donosos, Paz y Miños, López,
Dálavos and so forth families were all more or less neighbors in
Quito; societies were more structured then. Everybody went to the
same churches, theatre, events, etc. and everybody who was anybody
know everybody else. There are virtues and disadvantages in that, but
that's the way it was. When Dolores Zambrano died in 1869, Felicísimo
López and his brother Francisco were both witnesses to her will.
People got together, played cards, danced, acted as eachother's
doctor, lawyer, etc. Amalia and the López brothers had in common a
great love of learning and education; books that belonged to these
people that I saw or have myself reveal fairly active though
circumscribed tastes, with a penchant towards history and natural sciences
and a good deal of current European philosophy. One can only partially
underestimate the smallness of numbers of similarly inclined people
in mid 19th century Quito. It is therefore easy to understand how the
still young Amalia, wife of an older and semi-invalid man, could choose
no more apt person as her second husband than Francisco Mariano López
who was in case I've not mentioned it before, the _older_ brother of
Felcísimo. Of this second marriage there were three children (see
chart 2), of whom Malvina alone survived into modern times. Malvina
was an interesting lady, of whom more later; she was also the last of
her generation and line. In genealogical terms, she's double related to us
(except of course to Lola's descendants) because she was Papa's half-sister,
and therefore aunt to Stella, George, etc., _and_ Nana's first
cousin. In accordance with the system I tediously tried to describe
earlier, relatives on both sides nicknamed her ``la tía universal.''
It was she who after the death of Miguel Angel López brought up his
children, as mentioned earlier, and it was she, in Quito, who was one
of the three old lady sisters group in Quito, i.e., Diocelina, Rosario and
Malvina. To complete the picture a bit, Diocelina married a man named
Trajano Hurtado (no relation to the aforementioned travellin' man) and
they had a bunch of children, of whom the youngest was Enrique, whom some
of you will remember. Rosario was first married to a Danish pharmacist
named Emil Stahlschmidt and there were two children, Lucila and
Guillermo. Stahlschmidt died, also of liver/kidney/booze/shortness of breath,
and Rosario later remarried; his name was José Dálavos and [they had] three children:
Homero, Edma and Amaya. Some will remember meeting Homero; Edma was very
nice, never married, and was a great friend and frequent visitor with
Malvina and Enid. Amaya married a Chilean and lives or lived there; she
had a son named José with whom I exchanged a couple of letters in the
early 60's. But there are more interesting aspects to all this.

I've seen a picture of José Manuel Paz y Miño in Quito, a large
framed mezzotint kind of thing at Enrique's house; he looked like Andrew
Jackson with a beard, a white beard, a long white beard. The kind of
beard that no one of predominantly Indian, or if you wish, Latino,
ancestry could raise.
In short, a white man, probably ``pure,'' much like the Guayaquil
grandees I mentioned in connection with Mamita. Amalia, it will be
recalled, was probably half white and half white-and-something, so that's
the statistical side of it. I say all this is a purely statistical
sense; I've often heard people say ``I'm one eighth Apache,'' or ``one sixteenth
Micmac...'' no, really... and it points out a cultural difference we here
have with Latin America. The mixing and blending in some areas of the
societies there isn't retraceable, nor noteworthy, nor really paid
much attention to. It just _is_. While the Spaniards did awful things
in South America, they didn't exterminate the native population as
other Europeans did in North America. In broad terms, colour probably
increases or decreases according to social class, and not unfamiliarly
so. One can picture the chagrin of some Yankee worthy at seeing his
daughter marry one of those _(Fill in your own)_ fellas. It all has
to do with how long one had been around and more of less in control of
things. José Manuel had many brothers, and there are Paz y Miños in
Quito, and Pazmiños in D.C. and elsewhere, and when Rosario Paz y Miño
v. de Stahlschmidt, later de Dávalos died, two Paz y Miño cousins paid
their respects, but there has never been any contact with any of those
families, either on Papa's part or that of any of the Hurtados, outside
of courtesy calls at wakes, etc.

Whereas there is a strong family resemblance between the children
of both Amalia's marriages, there is no trace of that face (José
Manuel) in anybody descended from Papa known to me, and I'm the only
person now living who had met almost all of them. While Papa resembled both
Diocelina and Rosario, he was most like Malvina and her brother Julio.
Nana told me that when Ann's mother met Malvina, she was taken aback
by the overpowering resemblance to Papa; she of course knew them both
in old age and at a span of years, but it was probably very striking
throughout their lives. Papa was ten years older than Malvina. I don't
know when Amalia married Francisco, but I do know that it was a very
happy marriage until her death in 1913. I believe what the people who
knew them told me about them. Papa's surviving correspondence with
Francisco is very warm, even in terms of the flowery style of the times.
No ``step'' seems to have preceded either the ``-father'' or ``-son'' in their
relationship. Nana also recalled Francisco, her beloved _tío Pancho_, with
the greatest fondness, perhaps despite the fact that it was he who caused
her first meeting with Papa. He was, like his brother Felicísimo, a
free-thinker, a Liberal, etc., etc., etc., and had done his part to achieve
the triumph of Alfaro and the Liberals in 1895, for which he was rewarded
with some appointments; he was the Postmaster General for a while, and
Minister of this or that at one time. By training, he was a lawyer
(cf. the reference to his being present at Dolores Zambrano's testamenting
in 1869) and consequently had a good income. Amalia had inherited some
property from Paz y Miño in the city, plus a small estate named _Carretas_
(carts) just outside Quito, so she was rather well-off in her own right,
which was to cause a rather nasty and prolonged family squabble over
her will, which in turn required Papa to return to Quito in 1913. It
was with the small legacy he received that Papa made the downpayment on
2114 Glenwood Road when he returned to Brooklyn in 1918. And thereby
hangs a tale whose _raison d'être_ is to explain the great paucity of
contacts between the Pazmiño kids in Brooklyn and their many Hurtado and
Stahlschmidt and Dávalos first cousins in Quito.

From all these antecedents, and familiar with the predilection for
intermarriage, legitimate, on both sides of the family, and after many
hours of perusal of the accompanying and many, many other photographs,
my intuition comples me to declare that almost certainly Papa was not
the son of José Manuel Paz y Miño, and that his stepfather was also his
natural father, that he was therefore full brother to Julio and Malvina
and consequently first cousin to Nana in blood as well as name. I first
reached this conclusion years ago and asked Nana about it a couple of
times. I never really did get a definite answer one way or the other,
but I recall that Nana only gave a semi-``Bah'' about it once, and
another time she just smiled and shook her head. The following pages
show most of the people mentioned above, so you can pore over the
pictures and draw your own conclusions.

Notice how all Amalia's children have her distinct rather wide
mouth; notice too the very dignified oval portrait of Diocelina, dated
August 1, 1897 in Quito, and how very much she reminds one of Stella.
One can see a clear relation among Diocelina, Malvina, Víctor, Julio
and Doña Amalia, but although Rosario has the same mouth and curly hair,
the rest of the face says something else enitrely. (The smaller photo of
Rosario was dated August 21, 1897, in Quito.) The photo of Julio César
has a note on the back to the effect that he died in Guayaquil on June
8, 1896 at the age of 17, so please correct my erroneous entry on chart
2. He died of yellow fever, and Nana recalled that when the doctors
wanted to administer enema to him to clear out his system (I presume
this was a contemporary practice) he refused; she attributed his death
to this decision and I think it coloured her medical philosophy forever.
The four pictures of Víctor Manuel show him at various stages; the first
is dated Quito, December 20, 1895, the second Brooklyn, March 10, 1902;
the third and fourth, also from Brooklyn, were probably taken in 1918
and 1943, the year before his death. Notice how black his hair still
was; when I last saw Malvina she was 88, and much of her still abundant
hair was still if not black, very, very dark grey. Unlike Víctor, and
later on his son Víctor, she never had recourse to that gallant but
unconvincing expedient of trying to deny baldness by letting the hair
get long on one side and then raking it over the top of the head. (I
remember once riding on a roller coaster with Víctor, who was of course
holding his hat in his hand, and having to stifle my laughter at seeing
all this long hair flapping in the wind, but only on one side. It
would have been unspeakably deflating to mention it at the time, but
it _was_ funny.) And lastly, the picture of the five young ladies was
taken on October 30, 1898, and Nana herself wrote their names down.
When we would look at these pictures and others, she would always say
how careless it was of people not to write on the back who the person(s)
in the picture were, just in case. A game for you all: of these ladies,
two are sisters-in-law, two are half-sisters, three are sisters, and
four are first cousins. Can you identify them all?

Sometime around 1910 Malvina married a man named Humberto Egas,
who was from Guayaquil and belonged to a family that were friends of
Felicísimo and Francisca. The marriage was childless and a flop, and
they divorced. But they were still married when Doña Amalia died in
1913. She left a substantial estate, and quarrels arose between
Diocelina and Rosario and their families on one side, and Malvina and
Humberto and the widowed Francisco on the other. Papa, who had been
living in Brooklyn since 1900, went back to Quito to join in the fray
and stayed for five years, leaving Nana and the children in the utmost
penury. He wanted Nana and the family to go back with him, but Nana
refused, in part because of the embarrassing nature of the trip. In
1912 the Liberals and Alfaro fell rather catastrophically; Alfaro and
many other government officials were killed and mutilated, and it was
some time before things settled down. By the time of Amalia's death
the Conservative government in power had offered amnesties and free
passage back to Ecuador to all those expatriate nationals who had
been connected with the preceding regime. The newspaper social columns,
which still tell of people coming and going today, would carry a
notation to the effect that so and so had just returned under the
government's repatriation/amnesty policy, which Nana thought would be too
humiliating. She later regretted this; in her last years, when the
poverty had become grinding, she would often tell me that she had
never wanted to come to this country in the first place, that the idea
was Abuelito's and Papa's and that in any event they had never intended
to stay in New York permanently. She was proud that she had never
become a citizen; I remember typing a letter for her to some Guayaquil
postal official, in which she complained about a letter of hers to a
cousin that had been ``lost;'' in it she described herself as ``una
ecuatoriana ausente de mi patria durante muchos años." It was at the
time 60 years since she had left Ecuador.

I think when Papa came back in 1918, it was very much against his
wishes and judgement. But he did and that's why we're all here. And
all that is part of the next chapter aka the Pazmiño López family.
The initial photographic documentation whereof follows herewith.

One final note: Doña Amalia's portrait, sent to Papa and Nana, is
inscribed thusly (I translate): ``The original (of this picture) loves
you argently and wishes you prosperity in the course of this miserable
life. Quito, August 6, 1908.'' When I read that to Nana, she laughed,
and said that Doña Amalia was being sarcastic, that she had a sense
of humour about life.
