INST(adc,immediate,0x69)
INST(adc,absolute,0x6d)
INST(adc,zero_page,0x65)
INST(adc,zero_page_x_indirect,0x61)
INST(adc,zero_page_indirect_y,0x71)
INST(adc,zero_page_x,0x75)
INST(adc,absolute_x,0x7d)
INST(adc,absolute_y,0x79)
INST(adc,zero_page_indirect,0x72)

INST(and,immediate,0x29)
INST(and,absolute,0x2d)
INST(and,zero_page,0x25)
INST(and,zero_page_x_indirect,0x21)
INST(and,zero_page_indirect_y,0x31)
INST(and,zero_page_x,0x35)
INST(and,absolute_x,0x3d)
INST(and,absolute_y,0x39)
INST(and,zero_page_indirect,0x22)

INST(cmp,immediate,0xc9)
INST(cmp,absolute,0xcd)
INST(cmp,zero_page,0xc5)
INST(cmp,zero_page_x_indirect,0xc1)
INST(cmp,zero_page_indirect_y,0xd1)
INST(cmp,zero_page_x,0xd5)
INST(cmp,absolute_x,0xdd)
INST(cmp,absolute_y,0xd9)
INST(cmp,zero_page_indirect,0xd2)

INST(eor,immediate,0x49)
INST(eor,absolute,0x4d)
INST(eor,zero_page,0x45)
INST(eor,zero_page_x_indirect,0x41)
INST(eor,zero_page_indirect_y,0x51)
INST(eor,zero_page_x,0x55)
INST(eor,absolute_x,0x5d)
INST(eor,absolute_y,0x59)
INST(eor,zero_page_indirect,0x52)

INST(lda,immediate,0xa9)
INST(lda,absolute,0xad)
INST(lda,zero_page,0xa5)
INST(lda,zero_page_x_indirect,0xa1)
INST(lda,zero_page_indirect_y,0xb1)
INST(lda,zero_page_x,0xb5)
INST(lda,absolute_x,0xbd)
INST(lda,absolute_y,0xb9)
INST(lda,zero_page_indirect,0xb2)

INST(ora,immediate,0x09)
INST(ora,absolute,0x0d)
INST(ora,zero_page,0x05)
INST(ora,zero_page_x_indirect,0x01)
INST(ora,zero_page_indirect_y,0x11)
INST(ora,zero_page_x,0x15)
INST(ora,absolute_x,0x1d)
INST(ora,absolute_y,0x19)
INST(ora,zero_page_indirect,0x12)

INST(sbc,immediate,0xe9)
INST(sbc,absolute,0xed)
INST(sbc,zero_page,0xe5)
INST(sbc,zero_page_x_indirect,0xe1)
INST(sbc,zero_page_indirect_y,0xf1)
INST(sbc,zero_page_x,0xf5)
INST(sbc,absolute_x,0xfd)
INST(sbc,absolute_y,0xf9)
INST(sbc,zero_page_indirect,0xf2)

INST(sta,absolute,0x8d)
INST(sta,zero_page,0x85)
INST(sta,zero_page_x_indirect,0x81)
INST(sta,zero_page_indirect_y,0x91)
INST(sta,zero_page_x,0x95)
INST(sta,absolute_x,0x9d)
INST(sta,absolute_y,0x99)
INST(sta,zero_page_indirect,0x92)

INST(brk,implied,0x00)
INST(clc,implied,0x18)
INST(cld,implied,0xd8)
INST(cli,implied,0x58)
INST(clv,implied,0xb8)
INST(dex,implied,0xca)
INST(dey,implied,0x88)
INST(inx,implied,0xe8)
INST(iny,implied,0xc8)
INST(nop,implied,0xea)
INST(pha,implied,0x48)
INST(php,implied,0x08)
INST(phx,implied,0xda)
INST(phy,implied,0x5a)
INST(pla,implied,0x68)
INST(plp,implied,0x28)
INST(plx,implied,0xfa)
INST(ply,implied,0x7a)
INST(rti,implied,0x40)
INST(rts,implied,0x60)
INST(sec,implied,0x38)
INST(sed,implied,0xf8)
INST(sei,implied,0x78)
INST(tax,implied,0xaa)
INST(tay,implied,0xa8)
INST(tsx,implied,0xba)
INST(txa,implied,0x8a)
INST(txs,implied,0x9a)
INST(tya,implied,0x98)

INST(bit,immediate,0x89)
INST(bit,absolute,0x2c)
INST(bit,zero_page,0x24)
INST(bit,zero_page_x,0x34)
INST(bit,absolute_x,0x3c)

INST(asl,absolute,0x0e)
INST(asl,zero_page,0x06)
INST(asl,accumulator,0x0a)
INST(asl,zero_page_x,0x16)
INST(asl,absolute_x,0x1e)

INST(dea,accumulator,0x3a)
INST(ina,accumulator,0x1a)

INST(dec,absolute,0xce)
INST(dec,zero_page,0xc6)
INST(dec,zero_page_x,0xd6)
INST(dec,absolute_x,0xde)

INST(inc,absolute,0xee)
INST(inc,zero_page,0xe6)
INST(inc,zero_page_x,0xf6)
INST(inc,absolute_x,0xfe)

INST(lsr,absolute,0x4e)
INST(lsr,zero_page,0x46)
INST(lsr,accumulator,0x4a)
INST(lsr,zero_page_x,0x56)
INST(lsr,absolute_x,0x5e)

INST(rol,absolute,0x2e)
INST(rol,zero_page,0x26)
INST(rol,accumulator,0x2a)
INST(rol,zero_page_x,0x36)
INST(rol,absolute_x,0x3e)

INST(ror,absolute,0x6e)
INST(ror,zero_page,0x66)
INST(ror,accumulator,0x6a)
INST(ror,zero_page_x,0x76)
INST(ror,absolute_x,0x7e)

INST(stx,absolute,0x8e)
INST(stx,zero_page,0x86)
INST(stx,zero_page_y,0x96)

INST(sty,absolute,0x8c)
INST(sty,zero_page,0x84)
INST(sty,zero_page_x,0x94)

INST(stz,absolute,0x9c)
INST(stz,zero_page,0x64)
INST(stz,zero_page_x,0x74)
INST(stz,absolute_x,0x9e)

INST(ldx,immediate,0xa2)
INST(ldx,absolute,0xae)
INST(ldx,zero_page,0xa6)
INST(ldx,zero_page_y,0xb6)
INST(ldx,absolute_y,0xbe)

INST(ldy,immediate,0xa0)
INST(ldy,absolute,0xac)
INST(ldy,zero_page,0xa4)
INST(ldy,zero_page_x,0xb4)
INST(ldy,absolute_x,0xbc)

INST(cpx,immediate,0xe0)
INST(cpx,absolute,0xec)
INST(cpx,zero_page,0xe4)

INST(cpy,immediate,0xc0)
INST(cpy,absolute,0xcc)
INST(cpy,zero_page,0xc4)

INST(bcc,relative,0x90)
INST(bcs,relative,0xb0)
INST(beq,relative,0xf0)
INST(bmi,relative,0x30)
INST(bne,relative,0xd0)
INST(bpl,relative,0x10)
INST(bra,relative,0x80)
INST(bvc,relative,0x50)
INST(bvs,relative,0x70)

INST(trb,absolute,0x1c)
INST(trb,zero_page,0x14)
INST(tsb,absolute,0x0c)
INST(tsb,zero_page,0x04)

INST(jsr,absolute,0x20)
INST(jmp,absolute,0x4c)
INST(jmp,absolute_indirect,0x6c)
INST(jmp,absolute_x_indirect,0x7c)
