SETLOCAL

IF NOT DEFINED ROOTDIR GOTO:EOF

IF NOT EXIST DOS\NUL MKDIR DOS
CD DOS

CALL %ROOTDIR%\DOS\DOS3X\BUILD
IF ERRORLEVEL 1 GOTO:EOF
REM CALL %ROOTDIR%\DOS\PRODOS\BUILD
REM IF ERRORLEVEL 1 GOTO:EOF

ENDLOCAL
