#
# Makefile for app1ci
# Copyright (C) 2009, by IPC, Fairfield, CT
#
# author: Chris Mosher
# creation date: 2009-01-16
#

#define the installation prefix
prefix := /opt/ipc/onems

# Define version of phpunit to use
PHPUNIT_VERSION := 3.3.9

# set MAIN_TEST to be the class that runs the entire suite of unit tests
MAIN_TEST := AllTests


VOBROOT := /usr/vobs

include $(VOBROOT)/ipc_build/include/php_component.mk
