SETLOCAL

SET ROOTDIR=%~dp0
SET ROOTDIR=%ROOTDIR:~0,-1%

SET CC65DIR=C:\apple2\windows_programs\assemblers\cc65\bin

IF NOT (%1)==(INC) RMDIR /Q /S BUILD

IF NOT EXIST BUILD\NUL MKDIR BUILD
CD BUILD



CALL %ROOTDIR%\DOS\BUILD
IF ERRORLEVEL 1 GOTO:EOF

REM CALL %ROOTDIR%\FIRMWARE\BUILD
REM IF ERRORLEVEL 1 GOTO:EOF

ENDLOCAL
