L("<HTML>\n")
L("\n")
L("<HEAD>\n")
L("<TITLE>%name%</TITLE>\n")
L("</HEAD>\n")
L("\n")
L("<BODY>\n")
L("<H1>%name%</H1>\n")
L("\n")
L("child of <B>%father%</B> and <B>%mother%</B>\n")
L("\n")
L("%events%\n")
L("<P><H3>events</H3>\n")
L("<TABLE BORDER=1 CELLSPACING=0>\n")
L("%event%\n")
L("<TR>\n")
L("<TD><FONT SIZE=2><B>%type%</B></FONT></TD>\n")
L("<TD NOWRAP><FONT SIZE=2>%date%</FONT></TD>\n")
L("<TD><FONT SIZE=2>%place%</FONT></TD>\n")
L("<TD><FONT SIZE=2>%note%</FONT></TD>\n")
L("<TD><FONT SIZE=1><CITE>%citation%</CITE></FONT></TD>\n")
L("</TR>\n")
L("%/event%\n")
L("</TABLE>\n")
L("%/events%\n")
L("\n")
L("%attributes%\n")
L("<P><H3>attributes</H3>\n")
L("<TABLE BORDER=1 CELLSPACING=0>\n")
L("%attribute%\n")
L("<TR>\n")
L("<TD><FONT SIZE=2><B>%type%</B></FONT></TD>\n")
L("<TD><FONT SIZE=2><B>%value%</B></FONT></TD>\n")
L("<TD NOWRAP><FONT SIZE=2>%date%</FONT></TD>\n")
L("<TD><FONT SIZE=2>%place%</FONT></TD>\n")
L("<TD><FONT SIZE=2>%note%</FONT></TD>\n")
L("<TD><FONT SIZE=1><CITE>%citation%</CITE></FONT></TD>\n")
L("</TR>\n")
L("%/attribute%\n")
L("</TABLE>\n")
L("%/attributes%\n")
L("\n")
L("%partnerships%\n")
L("<P><H3>partnerships</H3>\n")
L("%partnership%\n")
L("<P><B>partner: </B>%name%\n")
L("%events%\n")
L("<P><B>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;partnership events</B>\n")
L("<TABLE><TR><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>\n")
L("<TABLE BORDER=1 CELLSPACING=0>\n")
L("%event%\n")
L("<TR>\n")
L("<TD><FONT SIZE=2><B>%type%</B></FONT></TD>\n")
L("<TD NOWRAP><FONT SIZE=2>%date%</FONT></TD>\n")
L("<TD><FONT SIZE=2>%place%</FONT></TD>\n")
L("<TD><FONT SIZE=2>%note%</FONT></TD>\n")
L("<TD><FONT SIZE=1><CITE>%citation%</CITE></FONT></TD>\n")
L("</TR>\n")
L("%/event%\n")
L("</TABLE>\n")
L("</TD></TR></TABLE>\n")
L("%/events%\n")
L("%children%\n")
L("<P><B>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;children:</B>\n")
L("<TABLE><TR><TD>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>\n")
L("<TABLE BORDER=1 CELLSPACING=0>\n")
L("%child%\n")
L("<TR><TD>%name%</TD></TR>\n")
L("%/child%\n")
L("</TABLE>\n")
L("</TD></TR></TABLE>\n")
L("%/children%\n")
L("%/partnership%\n")
L("%/partnerships%\n")
L("\n")
L("</BODY>\n")
L("</HTML>\n")
