package video;

/*
 * Created on Jan 21, 2008
 */
public final class Lowpass_3_58_MHz
{
	/*
	Generated by:   http://www-users.cs.york.ac.uk/~fisher/mkfilter
	
	Summary
	You specified the following parameters:
	
	      filtertype 	= 	Bessel
	      passtype 	= 	Lowpass
	      ripple 	= 	
	      order 	= 	2
	      samplerate 	= 	14318181.818181818181818181818182
	      corner1 	= 	3579545.4545454545454545454545455
	      corner2 	= 	
	      adzero 	= 	3579545.4545454545454545454545455
	      logmin 	= 	
	*/

	private static final int GAIN = 6;
	int x0,x1,x2,x3,x4,x5,x6,y0,y1,y2,y3,y4,y5,y6;

	public int transition(final int next_input_value)
	{
		x0 = x1;
		x1 = x2;
		x2 = x3;
		x3 = x4;
		x4 = next_input_value / GAIN;

		y0 = y1;
		y1 = y2;
		y2 = y3;
		y3 = y4;

		y4 = x0+x4+((x1+x2+x3)<<1)-y2/12-(y3>>2);

        return y4;
	}
}
