#
# Makefile for lib1php
# Copyright (C) 2009, by IPC, Fairfield, CT
#
# author: Chris Mosher
# creation date: 2009-01-16
#

#define the installation prefix
prefix := /opt/ipc/onems

# define version of tools to use
PHPUNIT_VERSION := 3.3.9

# define our phpunit test-suite class
MAIN_TEST := AllTests


VOBROOT := /usr/vobs

include $(VOBROOT)/ipc_build/include/php_component.mk
