# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/playqmake

HEADERS += playqmake.h \
           memory.h \
           RAMInitializer.h 
SOURCES += playqmake.cpp \
           main.cpp \
           memory.cpp \
           RAMInitializer.cpp 
TEMPLATE = app
CONFIG += release \
warn_on \
thread \
qt
TARGET = ../bin/playqmake
