#
# Makefile for lib1java
# Copyright (C) 2009, by IPC, Fairfield, CT
#
# author: Chris Mosher
# creation date: 2009-01-22
#

# define the installation prefix
prefix := /opt/ipc/onems

# define the JAR file we are building
TARGET = $(component).jar

# Define versions of tools to use
JAVA_VERSION := 1.5.0_17
ANT_VERSION := 1.6.5
JUNIT_VERSION := 4.5

# define our junit test-suite class
MAIN_TEST := AllTests


VOBROOT := /usr/vobs

include $(VOBROOT)/ipc_build/include/java_component.mk
