#
# Makefile for onems
# Copyright (C) 2009, by IPC, Fairfield, CT
#
# author: Chris Mosher
# creation date: 2009-01-23
#

#define the installation prefix
prefix = /opt/ipc/$(component)


VOBROOT := /usr/vobs

include $(VOBROOT)/ipc_build/include/product_component.mk
