package chipset;
/*
 * Created on Aug 1, 2007
 */
/**
 * TODO
 *
 * @author Chris Mosher
 */
public enum Addressing
{
	SINGLE,
	INTERNAL_IMMEDIATE,
	INTERNAL_ZERO_PAGE,
	INTERNAL_ABSOLUTE,
	INTERNAL_INDIRECT_X,
	INTERNAL_ABSOLUTE_XY,
	INTERNAL_ZERO_PAGE_XY,
	INTERNAL_INDIRECT_Y,
	STORE_ZERO_PAGE,
	STORE_ABSOLUTE,
	STORE_INDIRECT_X,
	STORE_ABSOLUTE_XY,
	STORE_ZERO_PAGE_XY,
	STORE_INDIRECT_Y,
	RMW_ZERO_PAGE,
	RMW_ABSOLUTE,
	RMW_ZERO_PAGE_X,
	RMW_ABSOLUTE_X,
	MISC_PUSH,
	MISC_PULL,
	MISC_JSR,
	MISC_BREAK,
	MISC_RTI,
	JMP_ABSOLUTE,
	JMP_INDIRECT,
	RTS,
	BRANCH,
	IRQ,
	RESET,
	NMI
}
