== Building From Source



Linux is the primary development platform supported,
but Windows (MSYS) is minimally supported. It shouldn't
be too hard to port to Mac either.

To build epple2 from the source distribution,
you'll need to have the SDL development libraries installed.
See http://www.libsdl.org/[http://www.libsdl.org/] for information on SDL.
You'll need to download and install the ``Development Libraries''
for your platform (Win32 or Linux).



=== Linux

==== Set Up Build Environment

The exact steps for setting up the build environment will
differ from system to system. You will need to set up the following:

* Standards-compliant C\++ compiler, such as GNU g++
* X11 headers; look for _libX11-dev_ or similar package
* you may need X11 extensions; for Debian, _x11proto-xext-dev_ worked for me

As a sanity check for g++, type this at the shell prompt:

[source,sh]
--------
g++ --version
--------

As a sanity check for X11, make sure this file exists:

+/usr/include/X11/Xlib.h+

I had trouble with building SDL from sources without having
the X11 extensions installed, as shown in the above list. If
you are not building SDL from sources (see below), you may not need
the X11 extensions.


As a sanity check for X11 extensions, make sure this file exists:


+/usr/include/X11/extensions/XShm.h+

==== Install SDL

You should check your distribution's package library to see if it has
the SDL development libraries and install them from there.

If not, go to http://www.libsdl.org/[]
and find the download page. You can either download the ``Development
Libraries'' for Linux, in RPM format, and install that,
or download the source and proceed as follows.


Download the ``Source Code,'' for example: +SDL-1.2.13.tar.gz+
And save it to your home directory. At the bash prompt, go to your home
directory and untar the SDL archive:

[source,sh]
--------
$ cd
$ tar xzvf SDL-1.2.13.tar.gz
--------

Then follow the instructions to install SDL, for example:

[source,sh]
--------
$ cd SDL-1.2.13
$ ./configure
$ make
$ sudo make install
--------

==== Untar Epple ][ Source

Download the Epple ][ Source Distribution
and save it to your home directory. At the bash prompt, go to your home
directory and untar the epple2 source distribution tar file. For example:

[source,sh]
--------
$ cd
$ tar xzvf epple2-1.0.tar.gz
--------

==== Build Epple ][

Then build as follows. I recommend doing a VPATH build,
where you build into a different directory than the source
directory. To accomplish this, create a new directory for
building, somewhere, such as:

--------
$ cd
$ mkdir buildepple2
$ cd buildepple2
--------

Then run configure and make:

--------
$ ~/epple2-1.0/configure
$ make
$ sudo make install
--------

If all goes well, it will build without any errors.




=== Windows/MSYS

==== Install MinGW/MSYS

Install MSYS into +C:\msys\+

Install MinGW into +C:\msys\mingw\+

For more information on MinGW and MSYS, see http://www.mingw.org/[].

==== Install SDL

At http://www.libsdl.org/[] find the download page.
Download the ``Development Libraries'' for Win32/mingw, for example:

+SDL-devel-1.2.13-mingw32.tar.gz+ (Mingw32)

and save it to your MSYS home directory (for example, +C:\msys\home\Administrator+).
Run MSYS, and at the bash prompt, go to your home directory and
untar the SDL archive to your home directory:

[source,sh]
--------
$ cd
$ tar xzvf SDL-devel-1.2.13-mingw32.tar.gz
--------

Then follow the instructions to install SDL, for example:

[source,sh]
--------
$ cd SDL-1.2.13
$ make native
--------

==== Untar Epple ][ Source

Download the Epple ][ Source Distribution
and save it to your MSYS home directory (for example, +C:\msys\home\Administrator+).
Run MSYS, and at the bash prompt, go to your home directory and
untar the epple2 source distribution tar file. For example:

[source,sh]
--------
$ cd
$ tar xzvf epple2-1.0.tar.gz
--------

==== Build Epple ][

Then build as follows. I recommend doing a VPATH build,
where you build into a different directory than the source
directory. To accomplish this, create a new directory for
building, somewhere, such as:

[source,sh]
--------
$ cd
$ mkdir buildepple2
$ cd buildepple2
--------

Then run +configure+ from there. For the MSYS build to work,
you need some extra parameters to the build, and you could
also add some compiler options to optimize the build. For
example (from the +buildepple2+ directory you just created):

[source,sh]
--------
$ ~/epple2/configure --prefix= \
CXXFLAGS="-I/usr/include -O4 -msse3" \
CFLAGS="-I/usr/include" \
LDFLAGS="-L/usr/lib -mconsole -mthreads -mno-cygwin"
$ make
--------

If all goes well, it will build without any errors.
If you get errors about not finding +SDL.h+, make sure
SDL is installed, and make sure the configure command
is correct. (If you just run configure without the
options shown above, you will get this error at build time.)
The result of the build (on Windows platform) is

+installer/epple2.msi+

which is an installable file for Windows. To install
epple2, just double-click on this file from Explorer.
